export const DIGITAL_CATEGORIES = [
  'All Services',
  'Video Advertising',
  'Search & PPC',
  'Social & Reels',
  'Programmatic Display',
  'Enterprise Retainers',
];

export const DIGITAL_BASE_RATES = [
  {
    platform: 'YouTube',
    category: 'Video Advertising',
    pricingModel: 'CPM (Cost Per 1,000 Views)',
    baseRatePerUnit: 350,
    unitName: '1,000 Views',
    minUnits: 50, // 50,000 views
    iconName: 'Video',
    desc: 'High retention in-stream TrueView & non-skippable bumper ads',
  },
  {
    platform: 'Meta (Instagram & Facebook)',
    category: 'Social & Reels',
    pricingModel: 'CPM (Cost Per 1,000 Impressions)',
    baseRatePerUnit: 200,
    unitName: '1,000 Impressions',
    minUnits: 100, // 100,000 impressions
    iconName: 'Share2',
    desc: 'Full-screen 9:16 vertical reels, stories, and feed carousels',
  },
  {
    platform: 'Google Ads',
    category: 'Search & PPC',
    pricingModel: 'CPC (Cost Per Intent Click)',
    baseRatePerUnit: 40,
    unitName: 'Clicks',
    minUnits: 1000, // 1,000 intent clicks
    iconName: 'Search',
    desc: 'Top-of-page Google Search keyword capture & GDN banner display',
  },
  {
    platform: 'Programmatic DSP',
    category: 'Programmatic Display',
    pricingModel: 'CPM (Cost Per 1,000 Impressions)',
    baseRatePerUnit: 95,
    unitName: '1,000 Impressions',
    minUnits: 200, // 200,000 impressions
    iconName: 'Zap',
    desc: 'Real-time automated auction bidding across 2M+ publisher websites',
  },
  {
    platform: 'TikTok Ads',
    category: 'Social & Reels',
    pricingModel: 'CPM (Cost Per 1,000 Video Plays)',
    baseRatePerUnit: 240,
    unitName: '1,000 Plays',
    minUnits: 50, // 50,000 plays
    iconName: 'Radio',
    desc: 'Native in-feed video ads with trending music and sound-on experience',
  },
];

export const INITIAL_DIGITAL_SERVICES = [
  {
    id: 'ds_yt_01',
    title: 'YouTube In-Stream & Bumper Video Ads',
    category: 'Video Advertising',
    platform: 'YouTube',
    tagline: 'High-impact skippable & bumper video ads with verified view rates',
    durationDays: 30,
    originalPrice: 250000,
    discountedPrice: 200000,
    discountPercent: 20,
    discountLabel: '20% OFF Launch Promo',
    discountType: 'promo',
    estimatedReach: '650,000+ Targeted Video Views',
    cpm: 'Rs. 307 CPM',
    iconName: 'Video',
    colorTheme: 'danger',
    deliverables: [
      'Skippable TrueView & 6s Bumper Ads',
      'Audience In-Market & Demographic Filters',
      'Direct Click-Through CTA Overlays',
      'Full View-Rate & Conversion Tracking Report',
    ],
    specs: '16:9 1080p HD, MP4, Max 60s (15s recommended)',
  },
  {
    id: 'ds_goog_02',
    title: 'Google Search Ads & Display Network',
    category: 'Search & PPC',
    platform: 'Google Ads',
    tagline: 'High-intent keyword search campaigns and 2M+ website banner placements',
    durationDays: 30,
    originalPrice: 180000,
    discountedPrice: 153000,
    discountPercent: 15,
    discountLabel: '15% OFF Starter Pack',
    discountType: 'growth',
    estimatedReach: '85,000+ High-Intent Clicks & 1.2M Impressions',
    cpm: 'Rs. 127 CPM / High CTR',
    iconName: 'Search',
    colorTheme: 'primary',
    deliverables: [
      'Top-of-Page Google Search Keyword Ads',
      'Google Display Network (GDN) Responsive Banners',
      'Negative Keyword Filtering & Bid Automation',
      'Conversion Pixel & ROI Attribution Setup',
    ],
    specs: 'Responsive Search Ads + 300x250, 728x90, 300x600 Web Banners',
  },
  {
    id: 'ds_meta_03',
    title: 'Meta (Instagram & Facebook) Reels Blitz',
    category: 'Social & Reels',
    platform: 'Meta Ads',
    tagline: 'Viral 9:16 vertical short-form reels and feed sponsored carousel ads',
    durationDays: 21,
    originalPrice: 220000,
    discountedPrice: 165000,
    discountPercent: 25,
    discountLabel: '25% OFF Omnichannel Bundle',
    discountType: 'bundle',
    estimatedReach: '950,000+ Social Engagements & Impressions',
    cpm: 'Rs. 173 CPM',
    iconName: 'Share2',
    colorTheme: 'info',
    deliverables: [
      'Instagram Reels & Stories Full-Screen Placement',
      'Facebook Feed Carousel & Video Ad Integration',
      'Lookalike Audience & Interest AI Targeting',
      'Lead Generation & Direct Messenger CTA Routing',
    ],
    specs: '9:16 Vertical 1080x1920 MP4 & 1:1 Feed 1080x1080',
  },
  {
    id: 'ds_prog_04',
    title: 'Programmatic CPM Display Blitz',
    category: 'Programmatic Display',
    platform: 'DSP Network',
    tagline: 'Automated real-time bidding across 2,000,000+ premium publishers & apps',
    durationDays: 14,
    originalPrice: 320000,
    discountedPrice: 224000,
    discountPercent: 30,
    discountLabel: '30% OFF High-Volume Blitz',
    discountType: 'promo',
    estimatedReach: '2,500,000+ Premium Web & App Impressions',
    cpm: 'Rs. 89 CPM (Real-Time Bidding)',
    iconName: 'Zap',
    colorTheme: 'warning',
    deliverables: [
      'Automated Real-Time Auction Bidding (RTB)',
      'Placements on Dawn, Forbes, Geo, TechCrunch & Top Apps',
      'Hyper-Local Geo-Fencing & IP Targeting',
      'Brand Safety Whitelists & Anti-Fraud Verification',
    ],
    specs: 'HTML5 Rich Media, 970x250, 300x600, 320x50 Mobile Interstitials',
  },
  {
    id: 'ds_tiktok_05',
    title: 'TikTok Viral Spark & Top-View Ads',
    category: 'Social & Reels',
    platform: 'TikTok',
    tagline: 'Sound-on immersive creator video ads targeting Gen-Z & young professionals',
    durationDays: 14,
    originalPrice: 210000,
    discountedPrice: 168000,
    discountPercent: 20,
    discountLabel: '20% OFF Creator Pack',
    discountType: 'growth',
    estimatedReach: '800,000+ Sound-On Video Plays',
    cpm: 'Rs. 210 CPM',
    iconName: 'Radio',
    colorTheme: 'secondary',
    deliverables: [
      'In-Feed Native Video & Spark Boosted Posts',
      'Custom Hashtag & Trending Audio Integration',
      'Interactive Add-On Display Cards & Stickers',
      'Direct Profile & Landing Page Swipe-Up Triggers',
    ],
    specs: '9:16 Vertical Video with Original Audio, MP4',
  },
  {
    id: 'ds_ret_06',
    title: 'Omnichannel Digital Enterprise Retainer',
    category: 'Enterprise Retainers',
    platform: 'Full Omnichannel',
    tagline: 'Complete full-funnel digital management combining Search, Social, Video, and DSP',
    durationDays: 60,
    originalPrice: 650000,
    discountedPrice: 422500,
    discountPercent: 35,
    discountLabel: '35% Retainer Discount',
    discountType: 'bundle',
    estimatedReach: '5,000,000+ Omnichannel Impressions',
    cpm: 'Rs. 84 CPM Blended Rate',
    iconName: 'Sparkles',
    colorTheme: 'primary',
    deliverables: [
      'Simultaneous YouTube + Meta + Google + Programmatic Ads',
      'Dedicated Senior Media Buyer & Campaign Strategist',
      'Weekly Multi-Channel Attribution & Live Dashboards',
      'Unlimited Creative Variant A/B Testing & Copywriting',
    ],
    specs: 'All Standard Digital Formats Supported',
  },
];
