"""link users to advertisers

Revision ID: 8b7af827d41e
Revises: fee557fa929a
Create Date: 2026-08-20 16:32:26.967639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b7af827d41e'
down_revision = 'fee557fa929a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advertiser_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_advertiser_id'), ['advertiser_id'], unique=False)
        batch_op.create_foreign_key(None, 'advertisers', ['advertiser_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_advertiser_id'))
        batch_op.drop_column('advertiser_id')

    # ### end Alembic commands ###
