"""add creatives table

Revision ID: f22908873ded
Revises: 2edd7a95be76
Create Date: 2026-08-24 02:21:45.098947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22908873ded'
down_revision = '2edd7a95be76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_reference', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('dimensions', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_reference')
    )
    with op.batch_alter_table('creatives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creatives_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creatives_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_creatives_uploaded_by'), ['uploaded_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creatives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creatives_uploaded_by'))
        batch_op.drop_index(batch_op.f('ix_creatives_status'))
        batch_op.drop_index(batch_op.f('ix_creatives_campaign_id'))

    op.drop_table('creatives')
    # ### end Alembic commands ###
